name: flutter_gauge
description: A little widget that given an Observable gives you an updated FlutterGauge.
version: 1.0.7
author: alitorki2651@gmail.com
homepage: https://github.com/alitorki2651/flutter_gauge

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: '>=0.18.1'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
